# AP 155 Lab Exercise
---
## Exercise 4: Derivatives (Non-central and central difference approximations)

_Instructions_: 
- **Report figure:** Log-log plot of MAE vs $h$ using first-order forward-difference, backward-difference and central-difference formulas
- **Report discussion:** Explain the resulting shape of your figure. Explain which regime is dominated by mathematical truncation error and which is dominated by floating-point machine precision (subtractive cancellation). What are the optimal step sizes $h^*$ for each method? Looking outward, when is each method of differentiation suitable/appropriate?
      
- **Code**: Complete the codes and ensure they are functional, error-free, readable, and efficient (where needed). Include a concise markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name (Last Name, First Name)_: 
- _Student No._: 20XX-XXXXX
- _Section_: THR-TX-_

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

### Report figure

![](cat-meme-wave-emoji.gif)

EDIT ME. See instruction above for what to include. Insert caption here, a short description what the figure illustrates. The syntax in markdown for putting a figure is `![Description](local_file_name.png)` or `<img src="/path/to_image.jpg" alt="Alt text" width=45%>`. Make sure the figure has complete elements.

### Report discussion

EDIT ME. See instruction above for what to include. Insert your discussions here. Discuss your key results with ~150 words per question.

### Other comments

- EDIT ME
- A self reflection can be placed here.
- This portion is not graded.
- You may insert further questions here.

---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

### Problem:

Consider the function:
$$ f(x) = 10\cos(2\pi x - 5)e^{-x} \tag{1}.$$

(a) Start by analytically evaluating the first derivative and creating a function that plots the analytical first derivative with $257$ points from $0$ to $2\pi$.

(b) Create three functions that calculates the first derivative approximation using the forward, backward, and central difference formulas. *(Bonus, not required): Make the function flexible to non-evenly spaced data*

(c) To give yourself a visualization, plot (in a single figure), the three derivative approximations and the analytically derived function evaluated from $0$ to $2\pi$ with $257$ points. Test what happens when you vary the number of points.

(d) Create a function (or lambda function) that calculates the mean absolute error of two sets of data (the approximations vs analytical values) for a given $h$. The mean absolute error is given by
$$ \text{MAE} = \frac{1}{n}\sum_{i=1}^n |y_i -\tilde{y}_i|$$
where $n$ is the total number of points, $y_i$ is the approximated value, and $\tilde{y}_i$ is the analytical value.

(e) **[REPORT FIGURE]** Generate a plot of the MAE for the three approximations vs the spacing between points $h$. You can use $h\in[10^{-16}, 10^0]$. In this plot, there should be three curves: One for the forward, one for the backward, and one for the central difference approximation. It should look something like Fig 3.2 of Gezerlis.

#### Problem 1 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

#### EXTRA:
Try to create your own function $f$ and use the approximations to calculate its first derivative.

## Section 3 (Notes)

### Non-central difference formulas (First Derivative)

* Forward 
$$
f'(x_i) = \frac{f(x_{i+1}) - f(x_{x})}{h} + O(h)
$$

* Backward
$$
f'(x_i) = \frac{f(x_{i}) - f(x_{i-1})}{h} + O(h)
$$



### Central-difference formulas

* First Derivative
$$
f'(x_i) = \frac{f(x_{i+1}) - f(x_{i-1})}{2h} + O(h^2)
$$

* Second Derivative
$$
f''(x_i) = \frac{f(x_{i+1}) - 2f(x_{i}) + f(x_{i-1})}{h^2} + O(h^2)
$$

Note: to avoid confusion, think: $x_i$ is `x[i]`, and $h$ is the gap between `x[i+1]` and `x[i]`.


In [13]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.linspace(1, 10, 10)
print(x)

# I can move all values to the left/right using roll
x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
x_roll2 = np.roll(x, -1)
print(x_roll)

# then I could exploit array operations to get their difference
x_diff = (x_roll - x)[1:]
print(x_diff)
# Be careful with the boundaries!

x_diff2 = (x_roll2 - x_roll)[:]
print(x_diff2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-8.  2.  2.  2.  2.  2.  2.  2.  2. -8.]


In [1]:
# finitediff.py from Gezerlis

from math import exp, sin, cos

def f(x):
    return exp(sin(2*x))

def fprime(x):
    return 2*exp(sin(2*x))*cos(2*x)

def calcfd(f,x,h):
    fd = (f(x+h) - f(x))/h
    return fd

def calccd(f,x,h):
    cd = (f(x+h/2) - f(x-h/2))/h
    return cd

if __name__ == '__main__':
    x = 0.5
    an = fprime(x)
    hs = [10**(-i) for i in range(1,12)]
    fds = [abs(calcfd(f,x,h) - an) for h in hs]
    cds = [abs(calccd(f,x,h) - an) for h in hs]
    rowf = "{0:1.0e}{1:1.16f} {2:1.16f}"
    print("h abs. error in fd abs. error in cd")
    for h,fd,cd in zip(hs,fds,cds):
        print(rowf.format(h,fd,cd))

h abs. error in fd abs. error in cd
1e-010.3077044583376249 0.0134656094697734
1e-020.0260359156900742 0.0001350472493096
1e-030.0025550421497806 0.0000013505116288
1e-040.0002550180941236 0.0000000135077878
1e-050.0000254969542519 0.0000000001495843
1e-060.0000025492660578 0.0000000002500959
1e-070.0000002564334673 0.0000000011382744
1e-080.0000000255070782 0.0000000189018428
1e-090.0000003741732106 0.0000000699159992
1e-100.0000021505300500 0.0000021505300500
1e-110.0000332367747395 0.0000111721462455
